apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-myschool-deployment
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: front-myschool
  template:
    metadata:
      labels:
        app: front-myschool
    spec:
      containers:
        - name: front-myschool-container
          image: khawlacherni/frontapptest:latest
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: front-myschool-service
spec:
  selector:
    app: front-myschool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

